@extends('admin.layouts.app') @section('title','Referrals') @section('heading','Referrals') @section('breadcrumb','Marketing / Referrals')
@section('content')
@if(session('status'))<div class="admin-callout"><p class="admin-callout__title">Referral updated</p></div>@endif
@if($errors->any())<div class="mb-6 border border-[var(--color-error)] bg-white p-4 text-[var(--color-error)]">{{ $errors->first() }}</div>@endif
<div class="grid gap-6 xl:grid-cols-[22rem_minmax(0,1fr)]"><aside class="admin-panel self-start"><div class="admin-panel__head"><h2 class="admin-panel__title">Record referral</h2></div><form method="POST" action="{{ route('admin.referrals.store') }}" class="admin-panel__body space-y-4">@csrf
<div><label class="admin-label">Referring client</label><select name="referrer_client_profile_id" class="admin-input" required><option value="">Select client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->displayName() }} · {{ $client->referral_code ?: 'no code' }}</option>@endforeach</select></div>
<div><label class="admin-label">Referred person</label><input name="referred_name" class="admin-input" required></div><div><label class="admin-label">Email</label><input name="referred_email" type="email" class="admin-input"></div><div><label class="admin-label">Phone</label><input name="referred_phone" class="admin-input"></div><input type="hidden" name="status" value="pending"><input type="hidden" name="reward_points" value="0"><div><label class="admin-label">Notes</label><textarea name="notes" class="admin-input" rows="3"></textarea></div><button class="btn btn-primary w-full">Record referral</button></form></aside>
<div class="admin-panel"><div class="admin-panel__head"><div><h2 class="admin-panel__title">Referral pipeline</h2><p class="mt-1 text-sm text-[var(--admin-text-muted)]">Converting a referral awards the selected points once.</p></div></div><div class="admin-panel__body space-y-4">@forelse($referrals as $referral)<form method="POST" action="{{ route('admin.referrals.update',$referral) }}" class="border border-[var(--admin-border)] p-4">@csrf @method('PUT')<input type="hidden" name="referrer_client_profile_id" value="{{ $referral->referrer_client_profile_id }}"><div class="mb-4 flex flex-wrap items-start justify-between gap-3"><div><strong>{{ $referral->referred_name }}</strong><p class="text-sm text-[var(--admin-text-muted)]">Referred by {{ $referral->referrer?->displayName() }} · {{ $referral->created_at->format('d M Y') }}</p></div><span class="admin-status">{{ ucfirst($referral->status) }}</span></div><div class="grid gap-3 md:grid-cols-4"><input name="referred_name" class="admin-input" value="{{ $referral->referred_name }}" required><input name="referred_email" type="email" class="admin-input" value="{{ $referral->referred_email }}" placeholder="Email"><input name="referred_phone" class="admin-input" value="{{ $referral->referred_phone }}" placeholder="Phone"><select name="status" class="admin-input">@foreach(['pending','contacted','converted','declined'] as $status)<option value="{{ $status }}" @selected($referral->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select><input name="reward_points" type="number" min="0" class="admin-input" value="{{ $referral->reward_points }}" placeholder="Reward points"><input name="notes" class="admin-input md:col-span-2" value="{{ $referral->notes }}" placeholder="Notes"><button class="btn btn-secondary">Save referral</button></div></form>@empty<div class="admin-empty"><p class="admin-empty__title">No referrals recorded</p></div>@endforelse</div><div class="p-4">{{ $referrals->links() }}</div></div></div>
@endsection
