@extends('admin.layouts.app')
@section('title', 'Client record')
@section('heading', $client->user?->name)
@section('breadcrumb', 'Clinic / Clients / Record')
@section('content')
<div class="grid gap-6 lg:grid-cols-[0.9fr,1.1fr]">
<div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Profile</h2></div><div class="admin-panel__body space-y-4"><div><p class="text-label mb-1">Email</p><p>{{ $client->user?->email }}</p></div><div><p class="text-label mb-1">Phone</p><p>{{ $client->user?->phone ?: '—' }}</p></div><div><p class="text-label mb-1">Preferred branch</p><p>{{ $client->preferredBranch?->name ?: '—' }}</p></div><div><p class="text-label mb-1">Emergency contact</p><p>{{ $client->emergency_contact_name ?: '—' }}{{ $client->emergency_contact_phone ? ' · '.$client->emergency_contact_phone : '' }}</p></div><div><p class="text-label mb-1">Loyalty points</p><p>{{ $client->loyalty_points }}</p></div><div><p class="text-label mb-1">Notes</p><div class="border border-[var(--admin-border)] bg-[var(--admin-surface-muted)] p-4 whitespace-pre-line">{{ $client->notes ?: '—' }}</div></div></div></div>
<div class="space-y-6"><div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Recent appointments</h2></div><div class="admin-panel__body">@if($appointments->isEmpty())<p class="admin-empty__copy">No appointments yet.</p>@else<ul class="admin-activity-list">@foreach($appointments as $appointment)<li class="admin-activity-list__item"><span class="admin-activity-list__time">{{ $appointment->starts_at?->timezone(config('clinic.timezone'))->format('d M Y H:i') }}</span><span class="admin-activity-list__text">{{ $appointment->treatment?->name }} · {{ ucfirst(str_replace('_', ' ', $appointment->status->value ?? (string) $appointment->status)) }}</span></li>@endforeach</ul>@endif</div></div><div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Consultations and enquiries</h2></div><div class="admin-panel__body">@if($consultations->isEmpty())<p class="admin-empty__copy">No consultation or academy enquiry records yet.</p>@else<ul class="admin-activity-list">@foreach($consultations as $consultation)<li class="admin-activity-list__item"><span class="admin-activity-list__time">{{ $consultation->created_at?->timezone(config('clinic.timezone'))->format('d M Y H:i') }}</span><span class="admin-activity-list__text">{{ ucfirst(str_replace('_', ' ', $consultation->status)) }} · {{ ucfirst($consultation->preferred_channel) }}</span></li>@endforeach</ul>@endif</div></div></div>
</div>
@endsection
