@if($errors->any())<div class="admin-callout mb-5"><div><p class="admin-callout__title">Please check the material</p><ul class="admin-callout__copy">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif
<div class="admin-panel"><div class="admin-panel__body grid gap-5 md:grid-cols-2">
    <div><label class="admin-label" for="course_id">Course</label><select class="admin-input" id="course_id" name="course_id" required><option value="">Select course</option>@foreach($courses as $course)<option value="{{ $course->id }}" @selected((string)old('course_id', $material->course_id) === (string)$course->id)>{{ $course->name }}</option>@endforeach</select></div>
    <div><label class="admin-label" for="enrolment_id">Access</label><select class="admin-input" id="enrolment_id" name="enrolment_id"><option value="">Every enrolled student in the course</option>@foreach($enrolments as $enrolment)<option value="{{ $enrolment->id }}" @selected((string)old('enrolment_id', $material->enrolment_id) === (string)$enrolment->id)>{{ $enrolment->studentProfile?->user?->name }} — {{ $enrolment->course?->name }}</option>@endforeach</select><p class="mt-1 text-xs text-[var(--admin-text-muted)]">Choose one enrolment to make this visible only to that student.</p></div>
    <div class="md:col-span-2"><label class="admin-label" for="title">Title</label><input class="admin-input" id="title" name="title" value="{{ old('title', $material->title) }}" required></div>
    <div><label class="admin-label" for="type">Material type</label><select class="admin-input" id="type" name="type">@foreach(['document'=>'Document','worksheet'=>'Worksheet','guide'=>'Guide','video'=>'Video','link'=>'External link'] as $value=>$label)<option value="{{ $value }}" @selected(old('type', $material->type ?: 'document') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><label class="admin-label" for="file">Upload file</label><input class="admin-input" id="file" name="file" type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip,.jpg,.jpeg,.png,.mp4">@if($material->file_path)<p class="mt-1 text-xs text-[var(--admin-text-muted)]">Current: {{ basename($material->file_path) }}</p>@endif</div>
    <div class="md:col-span-2"><label class="admin-label" for="external_url">Or external resource URL</label><input class="admin-input" id="external_url" name="external_url" type="url" value="{{ old('external_url', $material->external_url) }}" placeholder="https://..."></div>
    <div class="md:col-span-2"><label class="admin-label" for="description">Description</label><textarea class="admin-input" id="description" name="description" rows="4">{{ old('description', $material->description) }}</textarea></div>
    <label class="admin-check md:col-span-2"><input type="checkbox" name="is_published" value="1" @checked(old('is_published', $material->is_published))> Publish now so eligible students can access it</label>
</div></div>
