@extends('admin.layouts.app')
@section('title', 'Appointment')
@section('heading', 'Appointment '.$appointment->reference)
@section('breadcrumb', 'Clinic / Appointments / Review')
@section('content')
@if (session('status'))<p class="mb-4 border border-[var(--color-success)] bg-white px-4 py-3 text-[var(--color-success)]">{{ session('status') }}</p>@endif
@if ($errors->any())<div class="mb-6 border border-[var(--color-error)] bg-white px-4 py-3 text-[var(--color-error)]"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 lg:grid-cols-[0.95fr,1.05fr]">
<div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Appointment details</h2></div><div class="admin-panel__body space-y-4"><div><p class="text-label mb-1">Client</p><p>{{ $appointment->clientProfile?->displayName() }} · {{ $appointment->clientProfile?->displayEmail() }}</p>@if($appointment->clientProfile?->displayPhone())<p class="text-sm text-[var(--color-soft-grey)]">{{ $appointment->clientProfile->displayPhone() }}</p>@endif @if($appointment->clientProfile?->isGuest())<p class="text-sm text-[var(--color-bronze)] mt-1">Guest booking (no account)</p>@endif</div><div><p class="text-label mb-1">Treatment</p><p>{{ $appointment->treatment?->name }}</p></div><div><p class="text-label mb-1">Practitioner</p><p>{{ $appointment->practitioner?->user?->name }}</p></div><div><p class="text-label mb-1">Branch</p><p>{{ $appointment->branch?->name }}</p></div><div><p class="text-label mb-1">Starts</p><p>{{ $appointment->starts_at?->timezone(config('clinic.timezone'))->format('d M Y H:i') }}</p></div><div><p class="text-label mb-1">Client notes</p><div class="border border-[var(--admin-border)] bg-[var(--admin-surface-muted)] p-4 whitespace-pre-line">{{ $appointment->client_notes ?: '—' }}</div></div></div></div>
<form method="POST" action="{{ route('admin.appointments.update', $appointment) }}" class="admin-form">@csrf @method('PUT')<div class="admin-panel mb-6"><div class="admin-panel__head"><h2 class="admin-panel__title">Workflow</h2></div><div class="admin-panel__body grid gap-4 md:grid-cols-2"><div><label class="admin-label" for="status">Status</label><select id="status" name="status" class="admin-input">@foreach(\App\Enums\AppointmentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status', $appointment->status->value ?? $appointment->status) === $status->value)>{{ ucfirst(str_replace('_', ' ', $status->value)) }}</option>@endforeach</select></div><div><label class="admin-label" for="amount_paid">Amount paid</label><input id="amount_paid" name="amount_paid" type="number" step="0.01" min="0" class="admin-input" value="{{ old('amount_paid', $appointment->amount_paid) }}"></div><div class="md:col-span-2"><label class="admin-label" for="cancellation_reason">Cancellation reason</label><input id="cancellation_reason" name="cancellation_reason" class="admin-input" value="{{ old('cancellation_reason', $appointment->cancellation_reason) }}"></div></div></div><div class="admin-panel mb-6"><div class="admin-panel__head"><h2 class="admin-panel__title">Internal notes</h2></div><div class="admin-panel__body"><textarea id="internal_notes" name="internal_notes" rows="5" class="admin-input">{{ old('internal_notes', $appointment->internal_notes) }}</textarea></div></div><div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Status history</h2></div><div class="admin-panel__body">@if($appointment->statusHistories->isEmpty())<p class="admin-empty__copy">No status changes recorded yet.</p>@else<ul class="admin-activity-list">@foreach($appointment->statusHistories->sortByDesc('created_at') as $history)<li class="admin-activity-list__item"><span class="admin-activity-list__time">{{ $history->created_at?->timezone(config('clinic.timezone'))->format('d M Y H:i') }}</span><span class="admin-activity-list__text">{{ ucfirst(str_replace('_', ' ', $history->from_status ?? 'new')) }} → {{ ucfirst(str_replace('_', ' ', $history->to_status)) }}</span></li>@endforeach</ul>@endif</div></div><div class="flex flex-wrap gap-3 mt-6"><button type="submit" class="btn btn-primary">Save appointment</button><a href="{{ route('admin.appointments.index') }}" class="btn btn-secondary">Back</a></div></form>
</div>
@endsection
