[program:deluxaesthetic-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/deluxaesthetic/current/artisan queue:work database --sleep=3 --tries=3 --timeout=120 --max-time=3600
directory=/var/www/deluxaesthetic/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/deluxaesthetic/shared/storage/logs/worker.log
stopwaitsecs=3600

