@extends('admin.layouts.app') @section('title','Loyalty programme') @section('heading','Loyalty programme') @section('breadcrumb','Marketing / Loyalty')
@section('content')
@if(session('status'))<div class="admin-callout"><p class="admin-callout__title">Loyalty balance updated</p></div>@endif
<div class="admin-metric-grid mb-6"><div class="admin-metric admin-metric--primary"><p class="admin-metric__label">Points in circulation</p><p class="admin-metric__value">{{ number_format($totalPoints) }}</p></div><div class="admin-metric"><p class="admin-metric__label">Members</p><p class="admin-metric__value">{{ $clients->total() }}</p></div><div class="admin-metric"><p class="admin-metric__label">Recent adjustments</p><p class="admin-metric__value">{{ $transactions->count() }}</p></div></div>
<form method="GET" class="admin-panel mb-6"><div class="admin-panel__body flex flex-wrap gap-3"><input name="search" class="admin-input max-w-lg" value="{{ $search }}" placeholder="Search client name or email"><button class="btn btn-primary">Search</button><a href="{{ route('admin.loyalty.index') }}" class="btn btn-secondary">Reset</a></div></form>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1.3fr)_minmax(22rem,.7fr)]">
<div class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Member balances</h2></div><div class="admin-panel__body" style="padding:0;overflow-x:auto"><table class="admin-table"><thead><tr><th>Client</th><th>Referral code</th><th>Balance</th><th>Adjust points</th></tr></thead><tbody>@forelse($clients as $client)<tr><td><strong>{{ $client->displayName() }}</strong><p class="text-xs text-[var(--admin-text-muted)]">{{ $client->displayEmail() }}</p></td><td>{{ $client->referral_code ?: '—' }}</td><td><strong>{{ number_format($client->loyalty_points) }}</strong> pts</td><td><form method="POST" action="{{ route('admin.loyalty.adjust',$client) }}" class="flex min-w-[22rem] gap-2">@csrf<input name="points" type="number" class="admin-input max-w-24" placeholder="+/-" required><input name="description" class="admin-input" placeholder="Reason for adjustment" required><button class="btn btn-secondary btn-sm">Apply</button></form></td></tr>@empty<tr><td colspan="4"><div class="admin-empty"><p class="admin-empty__title">No loyalty members found</p></div></td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $clients->links() }}</div></div>
<aside class="admin-panel self-start"><div class="admin-panel__head"><h2 class="admin-panel__title">Recent point activity</h2></div><div class="admin-panel__body divide-y divide-[var(--admin-border)]">@forelse($transactions as $transaction)<div class="py-3 first:pt-0"><div class="flex justify-between gap-3"><strong>{{ $transaction->client?->displayName() }}</strong><span class="{{ $transaction->points>=0?'text-[var(--admin-success)]':'text-[var(--admin-error)]' }}">{{ $transaction->points>=0?'+':'' }}{{ number_format($transaction->points) }}</span></div><p class="mt-1 text-xs text-[var(--admin-text-muted)]">{{ $transaction->description }} · {{ $transaction->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-[var(--admin-text-muted)]">No adjustments recorded yet.</p>@endforelse</div></aside></div>
@endsection
