@php($promotion=$promotion??null)
@if($errors->any())<div class="mb-6 border border-[var(--color-error)] bg-white p-4 text-[var(--color-error)]"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]"><div class="space-y-6">
<section class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Campaign message</h2></div><div class="admin-panel__body grid gap-4">
<div><label class="admin-label" for="title">Headline</label><input id="title" name="title" class="admin-input" value="{{ old('title',$promotion?->title) }}" required></div>
<div><label class="admin-label" for="subtitle">Supporting text</label><textarea id="subtitle" name="subtitle" class="admin-input" rows="3">{{ old('subtitle',$promotion?->subtitle) }}</textarea></div>
<div class="grid gap-4 md:grid-cols-2"><div><label class="admin-label" for="cta_label">Button label</label><input id="cta_label" name="cta_label" class="admin-input" value="{{ old('cta_label',$promotion?->cta_label) }}"></div><div><label class="admin-label" for="cta_url">Button URL</label><input id="cta_url" name="cta_url" class="admin-input" value="{{ old('cta_url',$promotion?->cta_url) }}" placeholder="/store"></div></div>
<div><label class="admin-label" for="coupon_code">Coupon code shown</label><input id="coupon_code" name="coupon_code" class="admin-input" value="{{ old('coupon_code',$promotion?->coupon_code) }}" placeholder="SUMMER20"></div>
</div></section>
<section class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Campaign artwork</h2></div><div class="admin-panel__body grid gap-5 md:grid-cols-2">
<div>@if($promotion?->imageUrl())<img src="{{ $promotion->imageUrl() }}" alt="" class="mb-3 h-36 w-full object-cover">@endif<label class="admin-label" for="image">Desktop banner</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" class="admin-input"><label class="admin-label mt-3" for="image_url">or image URL</label><input id="image_url" name="image_url" class="admin-input" placeholder="https://…"></div>
<div>@if($promotion?->mobileImageUrl())<img src="{{ $promotion->mobileImageUrl() }}" alt="" class="mb-3 h-36 w-full object-cover">@endif<label class="admin-label" for="mobile_image">Mobile banner</label><input id="mobile_image" name="mobile_image" type="file" accept="image/jpeg,image/png,image/webp" class="admin-input"><label class="admin-label mt-3" for="mobile_image_url">or mobile image URL</label><input id="mobile_image_url" name="mobile_image_url" class="admin-input" placeholder="https://…"></div>
</div></section></div>
<aside class="space-y-6"><section class="admin-panel"><div class="admin-panel__head"><h2 class="admin-panel__title">Placement & schedule</h2></div><div class="admin-panel__body space-y-4">
<div><label class="admin-label" for="placement">Website placement</label><select id="placement" name="placement" class="admin-input">@foreach(['sitewide'=>'Every page','home'=>'Homepage','store'=>'Store','academy'=>'Academy'] as $value=>$label)<option value="{{ $value }}" @selected(old('placement',$promotion?->placement??'sitewide')===$value)>{{ $label }}</option>@endforeach</select></div>
<div><label class="admin-label" for="starts_at">Starts</label><input id="starts_at" name="starts_at" type="datetime-local" class="admin-input" value="{{ old('starts_at',$promotion?->starts_at?->format('Y-m-d\\TH:i')) }}"></div>
<div><label class="admin-label" for="ends_at">Ends</label><input id="ends_at" name="ends_at" type="datetime-local" class="admin-input" value="{{ old('ends_at',$promotion?->ends_at?->format('Y-m-d\\TH:i')) }}"></div>
<div><label class="admin-label" for="priority">Priority</label><input id="priority" name="priority" type="number" min="0" max="999" class="admin-input" value="{{ old('priority',$promotion?->priority??10) }}"></div>
<div class="grid grid-cols-2 gap-3"><div><label class="admin-label" for="background_color">Background</label><input id="background_color" name="background_color" type="color" class="admin-input h-12" value="{{ old('background_color',$promotion?->background_color??'#171613') }}"></div><div><label class="admin-label" for="text_color">Text</label><input id="text_color" name="text_color" type="color" class="admin-input h-12" value="{{ old('text_color',$promotion?->text_color??'#ffffff') }}"></div></div>
<input type="hidden" name="is_active" value="0"><label class="admin-check"><input type="checkbox" name="is_active" value="1" @checked((bool)old('is_active',$promotion?->is_active??true))> Active campaign</label>
</div></section><div class="grid gap-3"><button class="btn btn-primary">{{ $promotion?'Save promotion':'Create promotion' }}</button><a href="{{ route('admin.promotions.index') }}" class="btn btn-secondary">Cancel</a>@if($promotion)<button type="submit" form="delete-promotion" class="btn btn-danger">Delete promotion</button>@endif</div></aside></div>
